# Generated by Django 5.0.1 on 2024-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Cake', 'Cake'), ('Ice Cream', 'Ice cream'), ('Shake', 'Shake')], max_length=10)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='images')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
